# Generated by Django 2.0.6 on 2018-07-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20180628_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='last_updated',
            new_name='话题排序',
        ),
        migrations.AddField(
            model_name='topic',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
