# Generated by Django 2.0.6 on 2018-07-05 14:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20180705_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='话题排序',
        ),
        migrations.AddField(
            model_name='topic',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='话题排序'),
            preserve_default=False,
        ),
    ]
